[versions]
agp = "8.6.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"

[libraries]
cardview = "androidx.cardview:cardview:1.0.0"
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext_junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }  # Đổi dấu '-' thành '_'
espresso_core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }  # Đổi dấu '-' thành '_'
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android_application = { id = "com.android.application", version.ref = "agp" }  # Đổi dấu '-' thành '_'
